name: Verify
on: 
  push:
    branches:
      - master
      - develop
  pull_request:
    

jobs:
  verify_module:
    name: Verify module
    strategy:
      matrix:
        terraform: [0.13.6]    
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:${{ matrix.terraform }}
    steps:
      - uses: actions/checkout@v2
      - run: terraform init -get -backend=false -input=false
      - run: terraform fmt -recursive -check=true -write=false

  verify_examples:
    name: Verify examples
    strategy:
      matrix:
        terraform: [0.13.6, 0.14.5, latest]
        example: ["runner-default", "runner-docker", "runner-pre-registered", "runner-public"]
    defaults:
      run:
        working-directory: examples/${{ matrix.example }}
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:${{ matrix.terraform }}
    steps:   
      - uses: actions/checkout@v2
      - run: terraform init -get -backend=false -input=false
      - run: terraform fmt -recursive -check=true -write=false
      - run: terraform validate

  release:
    if: contains('refs/heads/master', github.ref)
    name: Release
    needs: [verify_module, verify_examples]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          cp .release/* .
          yarn 
      - name: relesase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release --repositoryUrl https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
